### ISSUE TITLE
minor errors in css or jsx files require a rerun of npm run dev

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/datawheel-canon#81]
css examples:

```
.selector {
  background: red
}
.selector
  background: red;
}
```

**Comment by perpetualgrimace** [comment]
jsx example:

```
<div>
  <span>
</div>
```

**Comment by perpetualgrimace** [comment]
Terminal output on error:

```
🛑  SERVER WEBPACK ERROR

ModuleBuildError: Module build failed: SyntaxError: Expected corresponding JSX closing tag for <span> (142:12)

  140 |               <span className="search-results-heading-icon pt-icon pt-icon-users">
  141 |               {t("Search.UsersHeading")}
> 142 |             </h3>
      |             ^
  143 |             <ul className="search-results-list">
  144 |               {userList}
  145 |             </ul>

    at runLoaders (/Users/jf/DatawheelDev/codelife/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/jf/DatawheelDev/codelife/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/jf/DatawheelDev/codelife/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/jf/DatawheelDev/codelife/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/jf/DatawheelDev/codelife/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/jf/DatawheelDev/codelife/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/jf/DatawheelDev/codelife/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /Users/jf/DatawheelDev/codelife/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /Users/jf/DatawheelDev/codelife/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
BabelLoaderError: SyntaxError: Expected corresponding JSX closing tag for <span> (142:12)

  140 |               <span className="search-results-heading-icon pt-icon pt-icon-users">
  141 |               {t("Search.UsersHeading")}
> 142 |             </h3>
      |             ^
  143 |             <ul className="search-results-list">
  144 |               {userList}
  145 |             </ul>

    at transpile (/Users/jf/DatawheelDev/codelife/node_modules/babel-loader/lib/index.js:65:13)
    at Object.module.exports (/Users/jf/DatawheelDev/codelife/node_modules/babel-loader/lib/index.js:173:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codelife@1.0.0 dev: `canon-dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codelife@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
